### ISSUE TITLE
Crashes on windows

### ISSUE THREAD

**Issue by eric-wieser** [mitchgu/TAMProxy-pyHost#10]
Due to `TAMPSerial.__init__` calling `self.nonblocking()`, which is posix only. Things didn't seem to work without this line either though

**Comment by mitchgu** [comment]
hmm I think the nonblocking call actually isn't essential. Pyserial often has frustrating quirks though. I think I added that call in the hopes that it would be more consistent, and just stuck with it. Sometimes adding calls inbetween serial writes inexplicably make it work. For example, lines 125 and 126 in packet_controller.py. The if statement never actually evaluates true in practice,  but if I don't have those, pyserial jams up on my mac. I've yet to try testing on Windows.
