### ISSUE TITLE
Adding new objects while a continuous request is active never completes

### ISSUE THREAD

**Issue by mitchgu** [mitchgu/TAMProxy-pyHost#24]
This seems to be host machine specific, as I cannot reproduce the issue on my Mac. However, I have had reports from three teams of things of that nature. If anyone has some example sketches where this happens or additional insight that would be great.

**Comment by eric-wieser** [comment]
We're being hit by this intermittently right now

**Comment by eric-wieser** [comment]
Specifically, by adding two encoder devices

**Comment by mitchgu** [comment]
yeah I think another team was trying to do that as well. I still don't know what's up besides add requests not being sent in the packet controller when it has a continuous request. 

I'm thinking of sorta sidestepping this and also making stopping tamproxy cleaner by having a _serve_continuous event in the packet controller. The pc will only send continuous requests if the event is set. 

Then Sketches can set the event after setup has completed, and the event can be cleared immediately prior to stopping tamproxy

**Comment by eric-wieser** [comment]
Hmm, seems that rebuilding the teensy firmware on my machine solved it...

**Comment by eric-wieser** [comment]
Sounds like there's a problem in general with requests not getting through when continuous mode is on

**Comment by mitchgu** [comment]
yeah, that's what I had seen. idk why rebuilding the firmware would help though.

**Comment by eric-wieser** [comment]
I deleted that comment because it was untrue

**Comment by eric-wieser** [comment]
Seems the packet leaves `PacketController.transmit` but never returns in `PacketController.process_packet`

**Comment by mitchgu** [comment]
ok, turns out I can reproduce it with two encoders and yeah, it does seem to leave transmit. 
I'm glad it's not some issue with python queues and pipes. Hopefully it's a simple firmware bug.

**Comment by mitchgu** [comment]
I'm still not 100% sure what's going on, but I have a better idea:

If sliding window timeouts are enabled in `config.yaml`, one can get two encoders added consistently. But according to the logging, the second encoder's add request, along with the `window_size - 1` other continuous requests for the first encoder, all time out several times before the packet controller gets the response that the second encoder has been added successfully. Enabling timeouts saves this by retransmitting all the packets that have timed out until finally a response comes that confirms the second encoder has been added. When this response comes, the ID of the second encoder is usually around 8-12 instead of 1, what it's supposed to be. This suggests that the firmware actually added 8-12 identical encoders before the pyHost got one response confirming a successful encoder add.

One hypothesis I have is that creating an encoder in the firmware takes like an order of magnitude or greater more time than a typical read or write request, since it's actually creating an encoder object with the Encoder library. But this still leaves many questions such as why the add device confirmation response has ID 8-12, or why the first encoder add request times out

Changing the window_size to 1 consistently eliminates this problem.

My next steps will probably be not starting continuous requests until the setup of a sketch has completed running. Not a true fix but probably good enough at the moment.

**Comment by eric-wieser** [comment]
Might the serial recieve buffer on the arduino be overflowing?

**Comment by mitchgu** [comment]
I don't think that explains why the response gives a device ID >> 1. That implies that the firmware actually got all the retransmits and just sent a response for the last one. (or pyHost just got a response for the last one).

I implemented my indirect fix just now in dd9e39c. If you're not using the sketch classes, make sure to call `tamp.pf.pc.set_continuous_enable(True)` after creating all the devices.

**Comment by eric-wieser** [comment]
Yay, heisenbug. This "fixes" it:

``` diff
def transmit(self, pid, dest, payload):
    if self.tserial.out_waiting > 50:
        self.tserial.flush()
    raw_packet = self.encode_raw_packet(pid, dest, payload)
+   logger.debug('sent {}'.format(raw_packet))
    self.tserial.write(raw_packet)
```

**Comment by mitchgu** [comment]
... actually? just extra delay when transmitting?

**Comment by eric-wieser** [comment]
Here's another clue:

``` diff
diff --git a/tamproxy/comm/packet_controller.py b/tamproxy/comm/packet_controller.py
index 1803052..f0d2b51 100644
--- a/tamproxy/comm/packet_controller.py
+++ b/tamproxy/comm/packet_controller.py
@@ -129,6 +129,8 @@ class PacketController(Process):
         # transmit the next packet
         if len(self.en_route) < self.WINDOW_SIZE:
             packet = self.get_new_packet_to_send()
+            if self.next_send_pid in self.en_route:
+                logger.critical('Overwriting packet {} with {}'.format(self.en_route[self.next_send_pid][0], packet))
             if packet:
                 new_pid = self.next_send_pid
                 self.en_route[new_pid] = (packet, time())
@@ -145,6 +147,7 @@ class PacketController(Process):
         if self.tserial.out_waiting > 50:
             self.tserial.flush()
         raw_packet = self.encode_raw_packet(pid, dest, payload)
         self.tserial.write(raw_packet)

     def receive(self):

```

This message prints while it hangs

**Comment by eric-wieser** [comment]
Update: The arduino (receive) buffer is not overflowing, and the device is being added successfully. But python never hears about it

**Comment by eric-wieser** [comment]
Update2: The response packet it making it to the `Serial.print` calls, and they're not returning -1.

**Comment by mitchgu** [comment]
What's `Serial.print`?

**Comment by eric-wieser** [comment]
Sorry, I mean `write`, in `PacketController::transmit`

**Comment by mitchgu** [comment]
I feel like PySerial is at fault here. This might be related to why the establishing `HELLO` packets have to be sent. When I didn't have them, pyserial would never get a response for the first packets I would send.

**Comment by eric-wieser** [comment]
The teensy-side serial driver may also be buggy. I spent a whole internship trying to find whether a bug was in our code or the microcontroller serial driver

**Comment by mitchgu** [comment]
Yikes. Maybe I should have `enable_timeout` set to true by default in `config.yaml` with this in mind.

**Comment by eric-wieser** [comment]
Nailed it:

https://forum.pjrc.com/threads/29299-Losing-data-with-bi-directional-USB-Serial-communication-(Teensy-3-1)

Setting `TX_PACKET_LIMIT` to 16 and `NUM_USB_BUFFERS` to 24, ie doubling both, fixes things for me.

I'm not sure if this qualifies as a driver bug, seems like dropping data is by design

**Comment by eric-wieser** [comment]
In fact, just `NUM_USB_BUFFERS = 24` in `usb_defs.h` does the trick

**Comment by mitchgu** [comment]
Wow, that's great. It's `usb_desc.h`, right? This makes a lot of sense, such as why it only happens with continuous requests, and when adding an encoder. The encoder creation probably takes so long that the usb packet buffers get filled.

**Comment by eric-wieser** [comment]
Not sure I fully understand what's going on yet - there's a shared memory pool for tx and rx buffers, and it's not clear which one is failing to allocate

**Comment by eric-wieser** [comment]
The `Encoder` constructor has a `delayMicroseconds(2000);`, which is probably relevant here

**Comment by eric-wieser** [comment]
Ah, think I've got it. Your window size is 12. There are 12 usb buffers free to allocate on the teensy, and at least one of them is probably in use for tx, so 11 buffers are free.

I suspect that flushing the serial connection python-side causes each packet to take up an entire usb packet, or that pyserial is flushing the buffer behind the scenes.

If you change the window size to 8, it seems to be fine.

**Comment by mitchgu** [comment]
Huh, that makes sense. Maybe that is related to why I've experimentally found 12 to be the optimal window size. Ideally I'd like to increase `NUM_USB_BUFFERS` so that the firmware can support larger window sizes. I need to figure out a way to import the teensyduino headers before the `src` headers so that I can override the define though.

**Comment by eric-wieser** [comment]
I think you're onto a loser there, if you want to maintain compatibility with the arduino IDE, you can't mess with include paths to try and fix things. And because the header is included in another compilation unit, you can't affect the defines when included in that source file.

**Comment by eric-wieser** [comment]
Incidentally, I think the linux/osx/windows behaviour differences might be down to rules about flushing usb serial devices.

**Comment by mitchgu** [comment]
I thought of a workaround that seems to build properly, but doesn't fix the two encoder issue for me. Can you see anything wrong? https://github.com/mitchgu/TAMProxy-Firmware/commit/10cfda24baf9f03e79defe3468262063e6095e4d
